### ISSUE TITLE
maximum font size?

### ISSUE THREAD

**Issue by younitee** [weihanchen/angular-d3-word-cloud#2]
I notice with smaller viewports/resolutions the word/s with the largest font size/s sometimes drop off.  Is there a known issue/relationship between max font size and layout size?  Thanks.

PS, handy library, thanks!

**Comment by weihanchen** [comment]
Because the layout size is too small to cause the largest word size cannot fits in the available space, so there a known relationship between max font size and layout size.

I think the user should choose the appropriate proportion, if there are many maximum font, you should use a smaller font size ratio, or expand the layout ratio.
